#line 2 "MainScanner.cpp"

#line 4 "MainScanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer mainparser_create_buffer
#define yy_delete_buffer mainparser_delete_buffer
#define yy_flex_debug mainparser_flex_debug
#define yy_init_buffer mainparser_init_buffer
#define yy_flush_buffer mainparser_flush_buffer
#define yy_load_buffer_state mainparser_load_buffer_state
#define yy_switch_to_buffer mainparser_switch_to_buffer
#define yyin mainparserin
#define yyleng mainparserleng
#define yylex mainparserlex
#define yylineno mainparserlineno
#define yyout mainparserout
#define yyrestart mainparserrestart
#define yytext mainparsertext
#define yywrap mainparserwrap
#define yyalloc mainparseralloc
#define yyrealloc mainparserrealloc
#define yyfree mainparserfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE mainparserrestart(mainparserin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int mainparserleng;

extern FILE *mainparserin, *mainparserout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mainparsertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up mainparsertext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via mainparserrestart()), so that the user can continue scanning by
	 * just pointing mainparserin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when mainparsertext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int mainparserleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow mainparserwrap()'s to do buffer switches
 * instead of setting up a fresh mainparserin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void mainparserrestart (FILE *input_file  );
void mainparser_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE mainparser_create_buffer (FILE *file,int size  );
void mainparser_delete_buffer (YY_BUFFER_STATE b  );
void mainparser_flush_buffer (YY_BUFFER_STATE b  );
void mainparserpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void mainparserpop_buffer_state (void );

static void mainparserensure_buffer_stack (void );
static void mainparser_load_buffer_state (void );
static void mainparser_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER mainparser_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE mainparser_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE mainparser_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE mainparser_scan_bytes (yyconst char *bytes,int len  );

void *mainparseralloc (yy_size_t  );
void *mainparserrealloc (void *,yy_size_t  );
void mainparserfree (void *  );

#define yy_new_buffer mainparser_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        mainparserensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mainparser_create_buffer(mainparserin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        mainparserensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mainparser_create_buffer(mainparserin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define mainparserwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *mainparserin = (FILE *) 0, *mainparserout = (FILE *) 0;

typedef int yy_state_type;

extern int mainparserlineno;

int mainparserlineno = 1;

extern char *mainparsertext;
#define yytext_ptr mainparsertext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up mainparsertext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	mainparserleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[218] =
    {   0,
        0,    0,   67,   65,   63,   64,   36,   55,   65,   65,
       65,   65,   46,   47,   39,   37,   50,   38,   56,   40,
       58,   53,   52,   30,   51,   29,   57,   41,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   48,
       65,   49,   28,    0,    0,   59,    0,   42,   54,   35,
        0,    0,   45,   43,   44,    0,   62,   58,   32,   27,
       31,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   34,   33,
       60,    0,    0,   62,   57,   57,   57,   57,   57,   13,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   15,   57,   57,    0,   57,   57,   57,   61,    9,
       57,   57,   57,   57,   57,   57,   26,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,    0,   57,   57,
       22,   57,   57,    2,   57,   57,   57,   57,   57,   23,
       57,   57,   57,    0,   57,   57,   57,   57,    0,    0,
        1,   11,   57,   21,   57,   57,    8,   57,   57,   57,
       57,    0,   57,   57,   57,   57,    0,    0,    0,   57,
        7,   20,   57,   57,   57,   12,    0,    6,   57,   57,
       57,    0,    0,    0,   10,    3,   24,   57,    0,   57,
        0,   14,    0,    0,    0,   57,    0,    5,    0,   16,

        0,    0,   25,    4,    0,    0,    0,    0,   18,    0,
        0,   17,    0,    0,    0,   19,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
        1,   25,    1,   26,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   24,   35,   24,   24,   36,   37,   38,
       39,   40,   24,   41,   42,   43,   44,   45,   24,   46,
       24,   24,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       50,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   51,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    4,    5,    1,    1,
        1,    1,    1,    5,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    5,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[223] =
    {   0,
        0,    0,  244,  245,  245,  245,   30,   48,  237,  235,
      233,  215,  245,  245,  227,  225,  245,  222,  245,   42,
      218,  245,  245,  213,  212,  211,    0,  245,  193,   27,
      199,   18,  202,   20,  194,   33,  196,  192,  185,  245,
      177,  245,  245,  174,   57,  245,  220,  245,  245,  245,
      213,  212,  245,  245,  245,  208,    0,  201,  245,  245,
      245,    0,  179,   34,  189,   36,  173,  172,  171,  177,
      172,  169,  172,  168,   32,   37,   45,   40,  245,  245,
      245,  196,  190,    0,  170,  173,  176,  161,  174,    0,
      169,  168,  167,  163,  155,  155,  152,  160,  165,  147,

      148,    0,  158,  150,  158,  148,  154,  153,  245,    0,
      146,  153,  150,   35,  143,  139,    0,  147,  146,  142,
      148,  131,  147,  145,  140,  128,  129,  125,  141,  126,
        0,  138,  122,    0,  123,  120,  130,  122,  122,    0,
      122,  120,  119,  113,  124,  120,  118,  114,  114,   55,
        0,    0,  118,    0,  108,  107,    0,  116,  111,  115,
      105,  104,  103,  106,   99,  111,   98,   93,   98,   94,
        0,    0,  102,   92,   97,    0,  100,    0,   99,  102,
       87,   91,   89,   82,    0,    0,    0,   96,   84,   83,
       84,    0,   88,   79,   86,   76,   74,    0,   80,  245,

       78,   75,    0,  245,   80,   79,   64,   66,  245,   66,
       54,  245,   48,   60,   45,  245,  245,   90,   95,   81,
      100,  105
    } ;

static yyconst flex_int16_t yy_def[223] =
    {   0,
      217,    1,  217,  217,  217,  217,  217,  218,  217,  217,
      217,  219,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  220,  217,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  217,
      217,  217,  217,  217,  218,  217,  218,  217,  217,  217,
      217,  219,  217,  217,  217,  221,  222,  217,  217,  217,
      217,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  217,  217,
      217,  221,  217,  222,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

      220,  220,  220,  220,  217,  220,  220,  220,  217,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  217,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  217,  220,  220,  220,  220,  217,  217,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  217,  220,  220,  220,  220,  217,  217,  217,  220,
      220,  220,  220,  220,  220,  220,  217,  220,  220,  220,
      220,  217,  217,  217,  220,  220,  220,  220,  217,  220,
      217,  220,  217,  217,  217,  220,  217,  220,  217,  217,

      217,  217,  220,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,    0,  217,  217,  217,
      217,  217
    } ;

static yyconst flex_int16_t yy_nxt[297] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,    4,   28,    4,   27,   29,   30,
       31,   32,   33,   27,   34,   27,   27,   35,   27,   36,
       37,   38,   39,   27,   27,   27,   40,   41,   42,    4,
        4,   43,   46,   56,   64,   67,   71,   72,   57,   68,
       74,   46,   65,   69,   86,   89,  100,  107,   90,  102,
      101,  105,   47,   75,   87,  135,  103,  136,   91,  104,
       44,   47,  106,  108,  168,   62,  216,  215,  214,  169,
       45,   45,   45,   45,   45,   51,  213,  212,   51,   51,

       82,   82,   82,  211,   82,   84,  210,   84,   84,   84,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  134,  133,  132,  131,  130,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,

      115,  114,  113,  112,  111,  110,  109,   83,   99,   98,
       97,   96,   95,   94,   93,   92,   88,   85,   58,   83,
       51,   81,  217,   80,   79,   78,   77,   76,   73,   70,
       66,   63,   61,   60,   59,   58,   55,   54,   53,   52,
       50,   49,   48,  217,    3,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217

    } ;

static yyconst flex_int16_t yy_chk[297] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,   20,   30,   32,   34,   34,   20,   32,
       36,   45,   30,   32,   64,   66,   75,   78,   66,   76,
       75,   77,    8,   36,   64,  114,   76,  114,   66,   76,
        7,   45,   77,   78,  150,  220,  215,  214,  213,  150,
      218,  218,  218,  218,  218,  219,  211,  210,  219,  219,

      221,  221,  221,  208,  221,  222,  207,  222,  222,  222,
      206,  205,  202,  201,  199,  197,  196,  195,  194,  193,
      191,  190,  189,  188,  184,  183,  182,  181,  180,  179,
      177,  175,  174,  173,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  156,  155,  153,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  139,
      138,  137,  136,  135,  133,  132,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  116,
      115,  113,  112,  111,  108,  107,  106,  105,  104,  103,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,

       91,   89,   88,   87,   86,   85,   83,   82,   74,   73,
       72,   71,   70,   69,   68,   67,   65,   63,   58,   56,
       52,   51,   47,   44,   41,   39,   38,   37,   35,   33,
       31,   29,   26,   25,   24,   21,   18,   16,   15,   12,
       11,   10,    9,    3,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int mainparser_flex_debug;
int mainparser_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *mainparsertext;
#line 1 "MainScanner.l"
#line 3 "MainScanner.l"
#include <stdio.h>
#include <stdlib.h>
#include "MainParser.h"
#include "nodo.h"
#include <iostream>

using namespace std;

    int mainparsercolno = 0;
    #define YY_USER_ACTION { mainparsercolno += mainparserleng; }
#line 632 "MainScanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int mainparserlex_destroy (void );

int mainparserget_debug (void );

void mainparserset_debug (int debug_flag  );

YY_EXTRA_TYPE mainparserget_extra (void );

void mainparserset_extra (YY_EXTRA_TYPE user_defined  );

FILE *mainparserget_in (void );

void mainparserset_in  (FILE * in_str  );

FILE *mainparserget_out (void );

void mainparserset_out  (FILE * out_str  );

int mainparserget_leng (void );

char *mainparserget_text (void );

int mainparserget_lineno (void );

void mainparserset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int mainparserwrap (void );
#else
extern int mainparserwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( mainparsertext, mainparserleng, 1, mainparserout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( mainparserin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( mainparserin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, mainparserin))==0 && ferror(mainparserin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(mainparserin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int mainparserlex (void);

#define YY_DECL int mainparserlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after mainparsertext and mainparserleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 27 "MainScanner.l"


#line 822 "MainScanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! mainparserin )
			mainparserin = stdin;

		if ( ! mainparserout )
			mainparserout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			mainparserensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				mainparser_create_buffer(mainparserin,YY_BUF_SIZE );
		}

		mainparser_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of mainparsertext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 218 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 245 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(traer_rsv); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(clase_rsv); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(extiende_rsv); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(paratodos_rsv); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(protegido_rsv); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(privado_rsv); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(decattr_rsv); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(entero_rsv); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(bool_rsv); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(caracter_rsv); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(cadena_rsv); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(ninguno_rsv); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(def_rsv); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(retornar_rsv); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (ref_rsv); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (si_cumple_rsv); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (sino_intente); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (sino_cumple_rsv); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (repetir_mientras_rsv); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (detener_rsv); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (decarr_rsv); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (true_rsv); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (false_rsv); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (imprimir_rsv); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (instanciar_rsv); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (este_rsv); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (esigual); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 58 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (noigual); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 59 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (mayor); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 60 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (menor); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 61 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (mayorigual); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 62 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (menorigual); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (esnulo); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 64 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (orOp); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 65 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (andOp); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 66 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (notOp); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 67 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (mas); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 68 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (menos); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (por); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 70 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (divOp); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (potencia); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (numeralnumeral); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (masmas); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 75 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (menosmenos); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (porpor); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (par_a); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (par_c); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (llave_a); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (llave_c); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (coma); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (sig_igual); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (p_coma); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (dos_p); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (dolar); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (comillas); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (punto); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (id); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return (numero); }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 94 "MainScanner.l"
{ mainparserlval.st = strtok(mainparsertext, "\""); return(string_token); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "MainScanner.l"
{ mainparserlval.st = strdup(mainparsertext); return(caracter_token); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 96 "MainScanner.l"
{ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "MainScanner.l"
{ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "MainScanner.l"
{ }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 102 "MainScanner.l"
{mainparserlineno++; mainparsercolno=1;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "MainScanner.l"
{
 cout <<"Error léxico: "<< mainparsertext << " Fila: " << mainparserlineno << " Columna: " << mainparsercolno<< endl ; return (ERROR);
 }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "MainScanner.l"
ECHO;
	YY_BREAK
#line 1240 "MainScanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed mainparserin at a new source and called
			 * mainparserlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = mainparserin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( mainparserwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * mainparsertext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of mainparserlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					mainparserrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			mainparserrestart(mainparserin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) mainparserrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 218 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 218 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 217);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up mainparsertext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					mainparserrestart(mainparserin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( mainparserwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve mainparsertext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void mainparserrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        mainparserensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            mainparser_create_buffer(mainparserin,YY_BUF_SIZE );
	}

	mainparser_init_buffer(YY_CURRENT_BUFFER,input_file );
	mainparser_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void mainparser_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		mainparserpop_buffer_state();
	 *		mainparserpush_buffer_state(new_buffer);
     */
	mainparserensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	mainparser_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (mainparserwrap()) processing, but the only time this flag
	 * is looked at is after mainparserwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void mainparser_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	mainparserin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE mainparser_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) mainparseralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mainparser_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) mainparseralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in mainparser_create_buffer()" );

	b->yy_is_our_buffer = 1;

	mainparser_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with mainparser_create_buffer()
 * 
 */
    void mainparser_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		mainparserfree((void *) b->yy_ch_buf  );

	mainparserfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a mainparserrestart() or at EOF.
 */
    static void mainparser_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	mainparser_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then mainparser_init_buffer was _probably_
     * called from mainparserrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void mainparser_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		mainparser_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void mainparserpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	mainparserensure_buffer_stack();

	/* This block is copied from mainparser_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from mainparser_switch_to_buffer. */
	mainparser_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void mainparserpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	mainparser_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		mainparser_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void mainparserensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)mainparseralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mainparserensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)mainparserrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mainparserensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE mainparser_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) mainparseralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mainparser_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	mainparser_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to mainparserlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       mainparser_scan_bytes() instead.
 */
YY_BUFFER_STATE mainparser_scan_string (yyconst char * yystr )
{
    
	return mainparser_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to mainparserlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE mainparser_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) mainparseralloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in mainparser_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = mainparser_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in mainparser_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mainparsertext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		mainparsertext[mainparserleng] = (yy_hold_char); \
		(yy_c_buf_p) = mainparsertext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		mainparserleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int mainparserget_lineno  (void)
{
        
    return mainparserlineno;
}

/** Get the input stream.
 * 
 */
FILE *mainparserget_in  (void)
{
        return mainparserin;
}

/** Get the output stream.
 * 
 */
FILE *mainparserget_out  (void)
{
        return mainparserout;
}

/** Get the length of the current token.
 * 
 */
int mainparserget_leng  (void)
{
        return mainparserleng;
}

/** Get the current token.
 * 
 */

char *mainparserget_text  (void)
{
        return mainparsertext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void mainparserset_lineno (int  line_number )
{
    
    mainparserlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see mainparser_switch_to_buffer
 */
void mainparserset_in (FILE *  in_str )
{
        mainparserin = in_str ;
}

void mainparserset_out (FILE *  out_str )
{
        mainparserout = out_str ;
}

int mainparserget_debug  (void)
{
        return mainparser_flex_debug;
}

void mainparserset_debug (int  bdebug )
{
        mainparser_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from mainparserlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    mainparserin = stdin;
    mainparserout = stdout;
#else
    mainparserin = (FILE *) 0;
    mainparserout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * mainparserlex_init()
     */
    return 0;
}

/* mainparserlex_destroy is for both reentrant and non-reentrant scanners. */
int mainparserlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		mainparser_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		mainparserpop_buffer_state();
	}

	/* Destroy the stack itself. */
	mainparserfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * mainparserlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *mainparseralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *mainparserrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void mainparserfree (void * ptr )
{
	free( (char *) ptr );	/* see mainparserrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 107 "MainScanner.l"



